### ISSUE TITLE
超参数问题

### ISSUE THREAD

**Issue by willcococv** [ddlee-cn/LeRF-PyTorch#1]
感谢作者的工作，仔细阅读代码之后有个问题想请教一下：
在通过超参数计算weight的时候，是出于什么样的考虑通过  **2*rho-1**、**2*alpha-1**进行范围调整的？self.max_sigma的引入是出于什么样的考虑？谢谢
![image](https://github.com/user-attachments/assets/0b78a9d8-509e-47c5-94a8-53a0c55894d4)

![image](https://github.com/user-attachments/assets/ea94f164-37fd-490e-a8a7-6eaf8235bbe0)

**Comment by ddlee-cn** [comment]
Thanks for your interests.

1. Adjust the range of the LUT output from [0,1] to [-1,1].
2. Avoid divergence with a manual bound for division.
