### ISSUE TITLE
Question on the PSNR report

### ISSUE THREAD

**Issue by SL-042** [ddlee-cn/LeRF-PyTorch#2]
I have been attempting to replicate the findings presented in your study but I couldn't get the PSNR results shown in the paper.
In the paper for x1.5/x1.5 Set 5, the PSNR value is 38.30. For x1.5/x1.5 Set 14, the PSNR value is  34.59.
However, I got 34.72 and 31.34 for each respectively. 
I show the results from the paper and the results I got.
I guess it's caused by misalignment between images.
I used resize function in resize_right/resize_right.py for downsampling.
For example, if i want to downsample with scale 1.5, I used resize(input, scale_factors=(1/1.5, 1/1.5), out_shape=None,
           interp_method=interp_methods.cubic, support_sz=None,
           antialiasing=True, by_convs=False, scale_tolerance=None,
           max_numerator=10, pad_mode='constant')

I'd appreciate your help.
<img width="612" alt="PSNR" src="https://github.com/user-attachments/assets/35679f15-472b-4d29-b8ff-0e7ed6b9548d">
<img width="1085" alt="myPSNR" src="https://github.com/user-attachments/assets/0814c0ea-efdb-40a5-b94c-7890e1b6b52c">

**Comment by ddlee-cn** [comment]
Thanks for your interests. I believe I have already replied your email, thus I will close this issue here.
